### PR TITLE
Generated PNG app icons for different sizes

### PR DESCRIPTION
**Pull request by emvigo**
This pull request includes PNGs of different sizes that are useful to be included for different Linux desktop environments to use in different contexts, such as menus, shortcuts, etc. This eases deployment in binary packages by distribution package mantainers.

### CODE REVIEW

**Comment by thokon00** [comment]
Please move them to /share/pixmaps
Thanks!

**Comment by emvigo** [comment]
OK, moved to /share/pixmaps!

**Comment by thokon00** [comment]
Thanks @emvigo, merged!

**Comment by emvigo** [comment]
Nice! @thokon00

**Pull request merged**
